name: mama_care
description: "A Flutter app for maternal care."

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
    

  # UI & Utilities
  cupertino_icons: ^1.0.8
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.8
  sizer: ^3.0.5
  smooth_page_indicator: ^1.1.0
  carousel_slider: ^5.0.0
  table_calendar: ^3.0.9

  # State Management
  
  get_it: ^8.0.0
  equatable: ^2.0.5

  # Firebase
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  google_sign_in: ^6.3.0
  firebase_messaging: ^15.1.1

  # Local Storage
  sqflite: ^2.3.3
  path: ^1.8.3

  # Location & Maps
  google_maps_flutter: ^2.5.0
  geolocator: ^14.0.0
  geocoding: ^3.0.0

  # Networking
  dio: ^5.4.0
  url_launcher: ^6.3.0

  # Dependency Injection
  injectable: ^2.1.1

  # Date/Time
  intl: ^0.19.0

  # JSON Serialization
  json_annotation: ^4.9.0 

  # Media
  video_player: ^2.8.1
  home_widget: ^0.7.0+1  # Updated to resolved version
  mailer: ^6.4.1
  flutter_local_notifications: ^19.0.0
  latlong2: ^0.9.1
  image_picker: ^1.1.2
  logging: ^1.3.0
  firebase_crashlytics: ^4.3.5
  firebase_analytics: ^11.4.5
  crypto: ^3.0.6
  sqflite_sqlcipher: ^3.1.0+1
  bcrypt: ^1.1.3
  logger: ^2.5.0
  provider: ^6.1.4
  path_provider: ^2.1.5
  uuid: ^4.5.1
  pin_code_fields: ^8.0.1
  http: ^1.3.0
  cached_network_image: ^3.4.1

  

  google_maps_flutter_platform_interface: any
  device_preview: ^1.2.0
  collection: ^1.19.1
  firebase_storage: ^12.4.5
  share_plus: ^11.0.0
  youtube_player_flutter: ^9.1.1
  timezone: ^0.10.0
  flutter_timezone: ^4.1.0
  flutter_dotenv: ^5.2.1
  connectivity_plus: ^6.1.4
  sqflite_common_ffi: ^2.3.5
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  
  analyzer: ^6.0.2

  # Code Generation
  build_runner: ^2.4.15
  injectable_generator: ^2.7.0
  json_serializable: ^6.9.4

  firebase_data_connect: any
flutter:
  uses-material-design: true

  fonts:
    - family: ProductSans
      fonts:
        - asset: assets/fonts/product-sans/Product Sans Regular.ttf
        - asset: assets/fonts/product-sans/Product Sans Italic.ttf
          style: italic
        - asset: assets/fonts/product-sans/Product Sans Bold.ttf
          weight: 700

  assets:
    - assets/images/article/
    - assets/images/exercise/
    - assets/images/pregnancy detail/
    - assets/images/logo.png
    - assets/images/google_icon.png
    - assets/svg/onboarding/
    - assets/svg/dashboard/
    - assets/svg/timeline/
    - assets/svg/suggested_food/
    - .env